#!/bin/sh
# Log into a FreeBSD jail by hostname.
# Usage: jlogin <hostname> [user]

if [ "x$1" = 'x' ]; then
    echo "USAGE: $0 <hostname> [user]"
else
    if [ "x$2" = 'x' ]; then
        LOGIN_USER=`whoami`
    else
        LOGIN_USER=$2
    fi

    JAIL_NAME=`/usr/sbin/jls -n \
        | /usr/bin/grep "hostname=$1" \
        | /usr/bin/grep -m 1 -o " name=[A-Za-z0-9_]* " \
        | /usr/bin/cut -d '=' -f 2`

    jexec $JAIL_NAME /usr/bin/login -f $LOGIN_USER
fi
